# Generated by Django 4.2.27 on 2025-12-31 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('accounts', '0002_wallet_wallettransaction_goalallocation'),
    ]

    operations = [
        # Supprimer l'ancien champ category (CharField)
        migrations.RemoveField(
            model_name='wallettransaction',
            name='category',
        ),
        # Ajouter le nouveau champ category (ForeignKey)
        migrations.AddField(
            model_name='wallettransaction',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='wallet_transactions',
                to='expenses.category',
                verbose_name='Catégorie'
            ),
        ),
        # Ajouter le lien vers Expense
        migrations.AddField(
            model_name='wallettransaction',
            name='expense',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wallet_transaction',
                to='expenses.expense',
                verbose_name='Dépense liée'
            ),
        ),
    ]
