# Generated by Django 4.2.27 on 2026-01-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wallet_expense_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('auto', 'Automatique (système)'), ('light', 'Clair'), ('dark', 'Sombre')], default='auto', max_length=10, verbose_name='Thème préféré'),
        ),
    ]
