# Generated by Django 4.2.27 on 2026-01-31 14:52

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Formats acceptés: JPG, PNG, GIF, WebP. Taille max: 5 MB.', null=True, upload_to='avatars/', validators=[accounts.validators.validate_image_file], verbose_name='Photo de profil'),
        ),
    ]
