# Generated by Django 4.2.27 on 2025-12-30 22:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du groupe')),
                ('description', models.TextField(verbose_name='Description')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant cible')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant collecté')),
                ('deadline', models.DateField(verbose_name='Date limite')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Complété'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('member', 'Membre')], default='member', max_length=20, verbose_name='Rôle')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Groupe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Adhésion',
                'verbose_name_plural': 'Adhésions',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GroupContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='paid', max_length=20, verbose_name='Statut de paiement')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de la contribution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='groups.group', verbose_name='Groupe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_contributions', to=settings.AUTH_USER_MODEL, verbose_name='Contributeur')),
            ],
            options={
                'verbose_name': 'Contribution de groupe',
                'verbose_name_plural': 'Contributions de groupe',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='member_groups', through='groups.Membership', to=settings.AUTH_USER_MODEL, verbose_name='Membres'),
        ),
    ]
