# Generated by Django 4.2.27 on 2025-12-30 22:50

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(default=groups.models.generate_invite_code, max_length=8, unique=True, verbose_name="Code d'invitation"),
        ),
    ]
