# Generated by Django 4.2.27 on 2025-12-31 00:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_groupexpense_groupexpensesplit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'objectif")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant cible')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant épargné')),
                ('deadline', models.DateField(verbose_name='Date limite')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Complété'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_savings_goals', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='groups.group', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': "Objectif d'épargne de groupe",
                'verbose_name_plural': "Objectifs d'épargne de groupe",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupSavingsContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de la contribution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('savings_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='groups.groupsavingsgoal', verbose_name="Objectif d'épargne")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_savings_contributions', to=settings.AUTH_USER_MODEL, verbose_name='Contributeur')),
            ],
            options={
                'verbose_name': "Contribution d'épargne de groupe",
                'verbose_name_plural': "Contributions d'épargne de groupe",
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
