# Generated by Django 4.2.27 on 2026-01-07 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupsavingsgoal_groupsavingscontribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcontribution',
            name='payment_status',
        ),
    ]
