# Generated by Django 4.2.27 on 2026-01-08 01:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_remove_groupcontribution_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'objectif")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('goal_type', models.CharField(choices=[('savings', 'Épargne'), ('project', 'Projet'), ('investment', 'Investissement'), ('travel', 'Voyage'), ('other', 'Autre')], default='savings', max_length=20, verbose_name="Type d'objectif")),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant cible')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant collecté')),
                ('deadline', models.DateField(verbose_name='Date limite')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Complété'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_goals', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='groups.group', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Objectif de groupe',
                'verbose_name_plural': 'Objectifs de groupe',
                'ordering': ['-created_at'],
            },
        ),
    ]
