# Generated by Django 4.2.27 on 2026-01-08 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_migrate_group_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcontribution',
            name='goal',
            field=models.ForeignKey(blank=True, help_text='Objectif spécifique vers lequel contribuer (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='groups.groupgoal', verbose_name='Objectif'),
        ),
    ]
