# Generated by Django 4.2.27 on 2026-01-08 01:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_groupcontribution_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Utilisez GroupGoal pour les nouveaux objectifs', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant collecté (obsolète)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='deadline',
            field=models.DateField(blank=True, help_text='Utilisez GroupGoal pour les nouveaux objectifs', null=True, verbose_name='Date limite (obsolète)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Utilisez GroupGoal pour les nouveaux objectifs', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant cible (obsolète)'),
        ),
    ]
